### ISSUE TITLE
Why there are no labels of hacktoberfest in closed pull request? 

### ISSUE THREAD

**Issue by ujjwalbhandarii** [iiitu-force/hacktoberfest22#230]
please label closed pull requests with hacktoberfest labels.

**Comment by akshatmittal61** [comment]
These labels are not necessary for every separate pull request.
The criteria for acceptance in hacktoberfest are **EITHER** the closed PR should have a label **OR** the repository should be labeled as a hacktoberfest participating repository (already done).

[Learn More](https://hacktoberfest.com/participation/#pr-mr-details)
